/* Константы типов бронирования места на парковке */
export const AUTO_RESERVATION = 'AUTO';
export const MANUAL_RESERVATION = 'MANUAL';

export const FIRST_PARKING_ROW_SPOTS_COUNT = 6;
export const SECOND_PARKING_ROW_SPOTS_COUNT = 4;
export const PARKING_SPOTS_COUNT = FIRST_PARKING_ROW_SPOTS_COUNT + SECOND_PARKING_ROW_SPOTS_COUNT;
export const CIRCLE_RADIUS = 10/Math.max(FIRST_PARKING_ROW_SPOTS_COUNT, SECOND_PARKING_ROW_SPOTS_COUNT);

export const RESERVATION_TIMEOUT = 15000;